apiVersion: v1
kind: Service
metadata:
  name: jg-first-aks-workflow
  namespace: jg-aks-demo
spec:
  type: LoadBalancer
  selector:
    app: jg-first-aks-workflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080